version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: messanger_db
    environment:
      POSTGRES_DB: "db_pg"
      POSTGRES_USER: "user_pg"
      POSTGRES_PASSWORD: "password_pg"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,PLAINTEXT_HOST://kafka:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "29092:29092"
      - "9092:9092"
    depends_on:
      - zookeeper
  kafka-ui:
      container_name: kafka-ui
      image: provectuslabs/kafka-ui:latest
      ports:
        - 8080:8080
      environment:
        - DYNAMIC_CONFIG_ENABLED='true'
        - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
        - KAFKA_CLUSTERS_0_NAME=local
      depends_on:
        - kafka
volumes:
  postgres_data: